# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/dawg/opencv_try

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/dawg/opencv_try

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dawg/opencv_try/CMakeFiles /home/dawg/opencv_try/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dawg/opencv_try/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named writvid

# Build rule for target.
writvid: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 writvid
.PHONY : writvid

# fast build rule for target.
writvid/fast:
	$(MAKE) -f CMakeFiles/writvid.dir/build.make CMakeFiles/writvid.dir/build
.PHONY : writvid/fast

#=============================================================================
# Target rules for targets named dispvid

# Build rule for target.
dispvid: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dispvid
.PHONY : dispvid

# fast build rule for target.
dispvid/fast:
	$(MAKE) -f CMakeFiles/dispvid.dir/build.make CMakeFiles/dispvid.dir/build
.PHONY : dispvid/fast

#=============================================================================
# Target rules for targets named DisplayImage

# Build rule for target.
DisplayImage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 DisplayImage
.PHONY : DisplayImage

# fast build rule for target.
DisplayImage/fast:
	$(MAKE) -f CMakeFiles/DisplayImage.dir/build.make CMakeFiles/DisplayImage.dir/build
.PHONY : DisplayImage/fast

#=============================================================================
# Target rules for targets named load

# Build rule for target.
load: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 load
.PHONY : load

# fast build rule for target.
load/fast:
	$(MAKE) -f CMakeFiles/load.dir/build.make CMakeFiles/load.dir/build
.PHONY : load/fast

#=============================================================================
# Target rules for targets named conden

# Build rule for target.
conden: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 conden
.PHONY : conden

# fast build rule for target.
conden/fast:
	$(MAKE) -f CMakeFiles/conden.dir/build.make CMakeFiles/conden.dir/build
.PHONY : conden/fast

#=============================================================================
# Target rules for targets named color_slider

# Build rule for target.
color_slider: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 color_slider
.PHONY : color_slider

# fast build rule for target.
color_slider/fast:
	$(MAKE) -f CMakeFiles/color_slider.dir/build.make CMakeFiles/color_slider.dir/build
.PHONY : color_slider/fast

#=============================================================================
# Target rules for targets named roi

# Build rule for target.
roi: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 roi
.PHONY : roi

# fast build rule for target.
roi/fast:
	$(MAKE) -f CMakeFiles/roi.dir/build.make CMakeFiles/roi.dir/build
.PHONY : roi/fast

color_slider.o: color_slider.cpp.o

.PHONY : color_slider.o

# target to build an object file
color_slider.cpp.o:
	$(MAKE) -f CMakeFiles/color_slider.dir/build.make CMakeFiles/color_slider.dir/color_slider.cpp.o
.PHONY : color_slider.cpp.o

color_slider.i: color_slider.cpp.i

.PHONY : color_slider.i

# target to preprocess a source file
color_slider.cpp.i:
	$(MAKE) -f CMakeFiles/color_slider.dir/build.make CMakeFiles/color_slider.dir/color_slider.cpp.i
.PHONY : color_slider.cpp.i

color_slider.s: color_slider.cpp.s

.PHONY : color_slider.s

# target to generate assembly for a file
color_slider.cpp.s:
	$(MAKE) -f CMakeFiles/color_slider.dir/build.make CMakeFiles/color_slider.dir/color_slider.cpp.s
.PHONY : color_slider.cpp.s

conden.o: conden.cpp.o

.PHONY : conden.o

# target to build an object file
conden.cpp.o:
	$(MAKE) -f CMakeFiles/conden.dir/build.make CMakeFiles/conden.dir/conden.cpp.o
.PHONY : conden.cpp.o

conden.i: conden.cpp.i

.PHONY : conden.i

# target to preprocess a source file
conden.cpp.i:
	$(MAKE) -f CMakeFiles/conden.dir/build.make CMakeFiles/conden.dir/conden.cpp.i
.PHONY : conden.cpp.i

conden.s: conden.cpp.s

.PHONY : conden.s

# target to generate assembly for a file
conden.cpp.s:
	$(MAKE) -f CMakeFiles/conden.dir/build.make CMakeFiles/conden.dir/conden.cpp.s
.PHONY : conden.cpp.s

dispvid.o: dispvid.cpp.o

.PHONY : dispvid.o

# target to build an object file
dispvid.cpp.o:
	$(MAKE) -f CMakeFiles/dispvid.dir/build.make CMakeFiles/dispvid.dir/dispvid.cpp.o
.PHONY : dispvid.cpp.o

dispvid.i: dispvid.cpp.i

.PHONY : dispvid.i

# target to preprocess a source file
dispvid.cpp.i:
	$(MAKE) -f CMakeFiles/dispvid.dir/build.make CMakeFiles/dispvid.dir/dispvid.cpp.i
.PHONY : dispvid.cpp.i

dispvid.s: dispvid.cpp.s

.PHONY : dispvid.s

# target to generate assembly for a file
dispvid.cpp.s:
	$(MAKE) -f CMakeFiles/dispvid.dir/build.make CMakeFiles/dispvid.dir/dispvid.cpp.s
.PHONY : dispvid.cpp.s

load.o: load.cpp.o

.PHONY : load.o

# target to build an object file
load.cpp.o:
	$(MAKE) -f CMakeFiles/load.dir/build.make CMakeFiles/load.dir/load.cpp.o
.PHONY : load.cpp.o

load.i: load.cpp.i

.PHONY : load.i

# target to preprocess a source file
load.cpp.i:
	$(MAKE) -f CMakeFiles/load.dir/build.make CMakeFiles/load.dir/load.cpp.i
.PHONY : load.cpp.i

load.s: load.cpp.s

.PHONY : load.s

# target to generate assembly for a file
load.cpp.s:
	$(MAKE) -f CMakeFiles/load.dir/build.make CMakeFiles/load.dir/load.cpp.s
.PHONY : load.cpp.s

roi.o: roi.cpp.o

.PHONY : roi.o

# target to build an object file
roi.cpp.o:
	$(MAKE) -f CMakeFiles/roi.dir/build.make CMakeFiles/roi.dir/roi.cpp.o
.PHONY : roi.cpp.o

roi.i: roi.cpp.i

.PHONY : roi.i

# target to preprocess a source file
roi.cpp.i:
	$(MAKE) -f CMakeFiles/roi.dir/build.make CMakeFiles/roi.dir/roi.cpp.i
.PHONY : roi.cpp.i

roi.s: roi.cpp.s

.PHONY : roi.s

# target to generate assembly for a file
roi.cpp.s:
	$(MAKE) -f CMakeFiles/roi.dir/build.make CMakeFiles/roi.dir/roi.cpp.s
.PHONY : roi.cpp.s

try.o: try.cpp.o

.PHONY : try.o

# target to build an object file
try.cpp.o:
	$(MAKE) -f CMakeFiles/DisplayImage.dir/build.make CMakeFiles/DisplayImage.dir/try.cpp.o
.PHONY : try.cpp.o

try.i: try.cpp.i

.PHONY : try.i

# target to preprocess a source file
try.cpp.i:
	$(MAKE) -f CMakeFiles/DisplayImage.dir/build.make CMakeFiles/DisplayImage.dir/try.cpp.i
.PHONY : try.cpp.i

try.s: try.cpp.s

.PHONY : try.s

# target to generate assembly for a file
try.cpp.s:
	$(MAKE) -f CMakeFiles/DisplayImage.dir/build.make CMakeFiles/DisplayImage.dir/try.cpp.s
.PHONY : try.cpp.s

writvid.o: writvid.cpp.o

.PHONY : writvid.o

# target to build an object file
writvid.cpp.o:
	$(MAKE) -f CMakeFiles/writvid.dir/build.make CMakeFiles/writvid.dir/writvid.cpp.o
.PHONY : writvid.cpp.o

writvid.i: writvid.cpp.i

.PHONY : writvid.i

# target to preprocess a source file
writvid.cpp.i:
	$(MAKE) -f CMakeFiles/writvid.dir/build.make CMakeFiles/writvid.dir/writvid.cpp.i
.PHONY : writvid.cpp.i

writvid.s: writvid.cpp.s

.PHONY : writvid.s

# target to generate assembly for a file
writvid.cpp.s:
	$(MAKE) -f CMakeFiles/writvid.dir/build.make CMakeFiles/writvid.dir/writvid.cpp.s
.PHONY : writvid.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... writvid"
	@echo "... dispvid"
	@echo "... DisplayImage"
	@echo "... load"
	@echo "... conden"
	@echo "... color_slider"
	@echo "... roi"
	@echo "... color_slider.o"
	@echo "... color_slider.i"
	@echo "... color_slider.s"
	@echo "... conden.o"
	@echo "... conden.i"
	@echo "... conden.s"
	@echo "... dispvid.o"
	@echo "... dispvid.i"
	@echo "... dispvid.s"
	@echo "... load.o"
	@echo "... load.i"
	@echo "... load.s"
	@echo "... roi.o"
	@echo "... roi.i"
	@echo "... roi.s"
	@echo "... try.o"
	@echo "... try.i"
	@echo "... try.s"
	@echo "... writvid.o"
	@echo "... writvid.i"
	@echo "... writvid.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

